export class Profile {
  birthMonth: string;
  birthDay: string;
  birthPlace: string;
  gender: string;
  height: string;
  weight: string;
  age: number;
  bloodType: string;
  color: string;
  constellation: string;
  handedness: string;
  hobby: string;
  title: string;
  cv: string;
  familyName: string;
  givenName: string;
  alternateName: string;
  familyNameKana: string;
  givenNameKana: string;
  alternateNameKana: string;
  bust: number | null;
  waist: number | null;
  hip: number | null;
  talent: string | null;
  attribute: string | null;
  division: string | null;
  favorite: string | null;
  description: string | null;
  type: string | null;
  category: string | null;
  shoeSize: string | null;
}
